######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 31 02:06:03 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp

QT += declarative \
	script
